### ISSUE TITLE
wifisocket_esp01_eagle.flash.bin

### ISSUE THREAD

**Issue by bvishaloaf** [SUPLA/ESP8266#13]
On flashing wifisocket_esp01_eagle.flash.bin binary, device some times after restart not latch with network. need to manual reset the device to get connect with wifi network

**Comment by przemyslawzygmunt** [comment]
This is old version. Change to latest

**Comment by bvishaloaf** [comment]
Please share link for new version for  ESP 01

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/ESP8266/tree/master/ESP-01_v1.8

**Comment by bvishaloaf** [comment]
Thanks Very Much
