### ISSUE TITLE
NO offline Mode

### ISSUE THREAD

**Issue by bvishaloaf** [SUPLA/ESP8266#16]
There is no option to control switch direct over wifi, if internet connection not working than not able to switch ON/Off device over same wifi (Mobile device & ESP device connected).

**Comment by przemyslawzygmunt** [comment]
There is no support for offline working. You can install your own supla server in local network.

SD Card Image of Supla Server for Raspberry PI
https://www.supla.org/download/SUPLA-SERVER-RBPI.zip

**Comment by msvsaran123** [comment]
Hi, 
    Can I install own supla server on Android phone.  Because in these days everyone may have an old android phone.  Again buying a raspberry pi is not budget friendly.

**Comment by przemyslawzygmunt** [comment]
Hi,

It is not possible.

 

Best Regards

**Comment by msvsaran123** [comment]
Ok. Thanks for your reply

**Comment by nikhilcuiet** [comment]
How to install on Raspberry PI. Please provide installation guide.
