### ISSUE TITLE
Docker Container For SUPLA server - new feature and improvements

### ISSUE THREAD

**Issue by scropion86** [SUPLA/ESP8266#17]
hi,

1. are you provide the server in Docker Image format?
i think this will make it easier to be deployed locally for small home servers like synology NAS , and Other similar devices.
 2. can you provide a Library which is compatible with ["esp8266/Arduino" ](https://github.com/esp8266/Arduino) which will be good for any DIY hardware.
as last time i tried to do it i have to download the Virtual machine and deal with the original SDK
which is hard for non professional user

thanks

**Comment by przemyslawzygmunt** [comment]
1. We plan provide it in the future
2. https://github.com/SUPLA/arduino (should works)
