### ISSUE TITLE
not define cfgmode pin

### ISSUE THREAD

**Issue by hirdeshsaxena** [SUPLA/ESP8266#20]
EgyIOT Board

EgyIOT_nossl_eagle.flash.bin-------->0x00000
EgyIOT_nossl_eagle.irom0text.bin---->0x40000

BAUDRATE: 115200
Flash Size: 512KByte
Flash speed: 40Mhz
SPI Mode: QIO

RELAY1 GPIO4
RELAY2 GPIO12
RELAY3 GPIO16

RGB (R) GPIO14
RGB (G) GPIO12
RGB (B) GPIO5

// CFG MODE ----------------------------------------

To bring the device into configuration
mode, press and hold button for at least 5 sec. When in configuration mode,
the device goes into Access Point mode.

In order to enter or change the settings, you need to:

- Sign in at https://cloud.supla.org (registration is free of charge)
- Connect to WiFi called „SUPLA-ESP8266” from any computer with a wireless network card and Internet browser.
- Open access page: http://192.168.4.1
- Enter user name and password to the WiFi through which the device will get Internet access.
- Enter Server address, Location ID and Location Password, which will be provided once you sign in at cloud.supla.org

**Comment by hirdeshsaxena** [comment]
what is the status of this

**Comment by hirdeshsaxena** [comment]
any solutin

**Comment by przemyslawzygmunt** [comment]
GPIO0
