### ISSUE TITLE
sample module development example

### ISSUE THREAD

**Issue by dipenpatel235** [SUPLA/ESP8266#39]
Hello..
is there any sample module development source code example available ?

If yes then please share link.
i have try to fine it but not found yet.

Thanks

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-espressif-esp

**Comment by dipenpatel235** [comment]
So using that repo given by you  i can write custom module ?

Thanks

**Comment by przemyslawzygmunt** [comment]
That's right

**Comment by dipenpatel235** [comment]
Ok...Thanks a lot
