### ISSUE TITLE
Inform server about state change - source code location

### ISSUE THREAD

**Issue by mdczaplicki** [SUPLA/ESP8266#41]
How can I inform server about state change?
I am writing my custom firmware for NodeMCU and it is working properly, but I have added a button to control LED and the state in the app is not affected by button.

Where can I find source code? I'd like to read how it is done in Sonoff WiFi Smart Switch, as there is also a button and it is changing state in the app.

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/arduino/blob/840bcf08ba753103e54ab2424d0f3cbee82db227/libraries/SuplaDevice/SuplaDevice.cpp#L1654

https://github.com/SUPLA/supla-espressif-esp/blob/b811b1030decba21188833b365640bad9d477609/src/user/supla_esp_devconn.c#L548

**Comment by mdczaplicki** [comment]
How do I get channel number?

**Comment by przemyslawzygmunt** [comment]
You assign channel numbers yourself. Read the code please.
