### ISSUE TITLE
Sonoff Switch firmware

### ISSUE THREAD

**Issue by T00ManySecrets** [SUPLA/ESP8266#9]
Ok so im using a sonoff switch with your firmware. Im using the button on it to turn on and off my light manually and i can use the app to control it remotely. 

Lets say i turn off the light by the app and the server registers it as off and in the meantime the switch loses connection.

I go into the room and turn on the light but as soon as the switch gets a connection back to the server the light turns off.

It follows the last state on the server. It would be better for it to follow the last manual state.

I have had this happen a lot of times.

**Comment by przemyslawzygmunt** [comment]
Hi. 

Please change firmware to this one
https://github.com/SUPLA/ESP8266/blob/master/sonoff/sonoff_ds18b20_v1.8.2.zip

Dnia 24.12.2016 o godz. 07:47 T00ManySecrets <notifications@github.com> napisał(a):

**Comment by T00ManySecrets** [comment]
So in 1.8.2 this is fixed? I have to use a DHT22 so i have to use the 1.8.0 for now.

**Comment by bvishaloaf** [comment]
So for 1.8.2 version which sensor we have to use & through which pin we have to connect
